receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'IRIS_CLOUDSQL'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
          action: keep
          regex: prom-example
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: (.+):(?:\d+);(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)

processors:
  resource:
    attributes:
    - key: "cluster"
      value: "CLUSTER_NAME"
      action: upsert
    - key: "namespace"
      value: "NAMESPACE_NAME"
      action: upsert
    - key: "location"
      value: "REGION"
      action: upsert


  #batch:
    # batch metrics before sending to reduce API usage
    #send_batch_max_size: 200
    #send_batch_size: 200
    #timeout: 5s

  #memory_limiter:
    # drop metrics if memory usage gets too high
    #check_interval: 1s
    #limit_percentage: 65
    #spike_limit_percentage: 20

exporters:
  googlemanagedprometheus:
    project: "PROJECT_ID"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      #processors: [batch, memory_limiter, resource, transform]
      exporters: [googlemanagedprometheus]