apiVersion: batch/v1
kind: CronJob
metadata:
  name: iris-cloudsql-exporter
  labels:
    app: iris-cloudsql-exporter
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: iris-cloudsql-exporter
            image: sween/iris-cloudsql-exporter:latest
            ports:
            - containerPort: 5000
            env:
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/gmp/key.json"
            - name: IRIS_CLOUDSQL_USERPOOLID
              valueFrom:
                secretKeyRef:
                  name: iris-cloudsql
                  key: userpoolid
            - name: IRIS_CLOUDSQL_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: iris-cloudsql
                  key: clientid
            - name: IRIS_CLOUDSQL_USER
              valueFrom:
                secretKeyRef:
                  name: iris-cloudsql
                  key: user
            - name: IRIS_CLOUDSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: iris-cloudsql
                  key: pass
            volumeMounts:
            - name: gmp-sa
              mountPath: /gmp
              readOnly: true
            volumes:
            - name: gmp-sa
              secret:
                secretName: gmp-test-sa
          restartPolicy: OnFailure