apiVersion: batch/v1
kind: CronJob
metadata:
  name: iris-cloudsql-exporter
  labels:
    app: iris-cloudsql-exporter
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: iris-cloudsql-exporter
            image: sween/iris-cloudsql-exporter:latest
            ports:
            - containerPort: 5000
            env:
            - name: IRIS_CLOUDSQL_USERPOOLID
              valueFrom:
                secretKeyRef:
                  name: iris-cloudsql
                  key: userpoolid
            - name: IRIS_CLOUDSQL_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: iris-cloudsql
                  key: clientid
            - name: IRIS_CLOUDSQL_USER
              valueFrom:
                secretKeyRef:
                  name: iris-cloudsql
                  key: user
            - name: IRIS_CLOUDSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: iris-cloudsql
                  key: pass
          restartPolicy: OnFailure